#let rv(x) = $bold(upright(#x))$
#let mv(x) = $hat(rv(#x))$
#let uvec(x) = $underline(#x)$
#let rvec(x) = $rv(uvec(#x))$
#let mvec(x) = $hat(rvec(#x))$
#let cvec(x) = $uvec(hat(#x))$
#let bvec(x) = $uvec(dash(#x))$
#let ervec(x) = $tilde(rvec(#x))$
#let zero = $uvec(0)$
#let mtx(x) = $bold(upright(#x))$
#let ermat(x) = $tilde(mtx(#x), size: #125%)$
#let bmat(x) = $dash(mtx(#x))$
#let ellip = math.cal($E$)
#let argmin = $arg min$
#let argmax = $arg max$
#let diag = math.op("diag")
#let Cov = math.op("Cov")
#let E = math.op("E")
#let rank = math.op("rank")
#let trace = math.op("trace")
#let Var = math.op("Var")
#let PDF = "probability density function"
#let Gauss = math.cal($N$)
#let Uniform = math.cal($U$)
