[package]
name = "ams-thesis"
version = "0.1.0"
entrypoint = "src/ams-thesis.typ"
authors = ["Kevin Kulot"]
license = "0BSD"
description = "A thesis template for the Autonomous Multisensor Systems group"
repository = "https://github.com/OVGU-AMS/Templates"
categories = ["thesis", "report"]
keywords = ["thesis", "master", "bachelor", "university", "OVGU", "Magdeburg", "Otto-von-Guericke-Universität"]
compiler = "0.14.0"
exclude = ["thumbnails"]

[template]
path = "."
entrypoint = "thesis.typ"
thumbnail = "thumbnails/p-01.png"
